### PR TITLE
Fix Segfault on Ruby 2.1.0

### PR DESCRIPTION
**Pull request by danbernier**
Inspired by this fix: https://github.com/rollbar/rollbar-gem/commit/ae36b448b5b3cf16aec64c3db24ccafc93371638

We were getting segfaults running in production under 2.1.0.

You can reproduce the segfault by running the specs for this gem under 2.1.0. 

This fixes it under 2.1.0, and specs still pass for 2.0.0 and 1.9.3. This also adds 2.1.0 to the .travis.yml.

### CODE REVIEW

**Comment by benjaminoakes** [comment]
:+1:

**Comment by danbernier** [comment]
Here's another PR that inspired this: https://github.com/collectiveidea/delayed_job/issues/616

**Comment by joshuap** [comment]
Cool, thanks! I'll release 0.0.4 today.

**Comment by danbernier** [comment]
Great, thanks!

On Tue, Jan 28, 2014 at 4:25 PM, joshuap notifications@github.com wrote:

> Merged #4https://github.com/honeybadger-io/delayed_job_honeybadger/pull/4
> .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/honeybadger-io/delayed_job_honeybadger/pull/4
> .

## 

twitter @danbernier
http://wordcram.org | http://newhaven.io

**Pull request merged**
